# Generated by Django 5.0.3 on 2024-03-12 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="route",
            options={"ordering": ("distance",)},
        ),
        migrations.AddField(
            model_name="flight",
            name="crews",
            field=models.ManyToManyField(related_name="flights", to="airport.crew"),
        ),
        migrations.AlterUniqueTogether(
            name="route",
            unique_together={("source", "destination")},
        ),
    ]
