# Generated by Django 5.0.3 on 2024-03-12 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("airport", "0003_alter_route_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="airplane",
            old_name="seats_in_rows",
            new_name="seats_in_row",
        ),
    ]
